"""Populate LESC team skills into skills table."""
from sqlalchemy import create_engine, text
from app.core.config import settings

engine = create_engine(settings.DATABASE_URL)

LESC_SKILLS = [
    "SESU_AE_FBA_ECM_REG_LESCWI_ENG", "SESU_AE_FBA_ECM_REG_LESC_ENG", "SESU_AE_MAT_ECM_REG_LESCWI_ENG",
    "SESU_AE_MAT_ECM_REG_LESC_ENG", "SESU_AU_FBA_ECM_REG_LESCWI_ENG", "SESU_AU_FBA_ECM_REG_LESC_CNCN_ILAC",
    "SESU_AU_FBA_ECM_REG_LESC_ENG", "SESU_AU_MAT_ECM_REG_LESCWI_ENG", "SESU_AU_MAT_ECM_REG_LESC_CNCN",
    "SESU_AU_MAT_ECM_REG_LESC_ENG", "SESU_BR_FBA_ECM_REG_LESCWI_ENG", "SESU_BR_FBA_ECM_REG_LESC_ENG",
    "SESU_BR_MAT_ECM_REG_LESCWI_ENG", "SESU_BR_MAT_ECM_REG_LESC_ENG", "SESU_EG_FBA_ECM_REG_LESCWI_ENG",
    "SESU_EG_FBA_ECM_REG_LESC_ENG", "SESU_EG_MAT_ECM_REG_LESCWI_ENG", "SESU_EG_MAT_ECM_REG_LESC_ENG",
    "SESU_EU_FBA_ECM_REG_LESCWI_ENG", "SESU_EU_FBA_ECM_REG_LESC_ENG", "SESU_EU_MAT_ECM_REG_LESCWI_ENG",
    "SESU_EU_MAT_ECM_REG_LESC_CNCN", "SESU_EU_MAT_ECM_REG_LESC_ENG", "SESU_EU_MAT_ECM_REG_STD_ENG_SDFR",
    "SESU_FE_MAT_ECM_REG_STD_ENG_SDFR", "SESU_IN_MAT_ECM_REG_LESCWI_ENG", "SESU_IN_MAT_ECM_REG_LESC_ENG",
    "SESU_IN_MAT_ECM_REG_STD_ENG_SDFR", "SESU_JP_MAT_ECM_REG_LESC_CNCN", "SESU_JP_MAT_ECM_REG_LESC_JPN",
    "SESU_MX_FBA_ECM_REG_LESCWI_ENG", "SESU_MX_FBA_ECM_REG_LESC_ENG", "SESU_MX_MAT_ECM_REG_LESCWI_ENG",
    "SESU_MX_MAT_ECM_REG_LESC_ENG", "SESU_NAAE_LESC_ECM_911_CH_ENGLISH_ME-FBA", "SESU_NAAE_LESC_ECM_911_CH_ENGLISH_ME-MAT",
    "SESU_NAAE_LESC_ECM_REG_CH_ENGLISH_ME-FBA", "SESU_NAAE_LESC_ECM_REG_CH_ENGLISH_ME-MAT", "SESU_NAAU_LESC_ECM_REG_CH_CN-CHINESE_AU-ILAC",
    "SESU_NAAU_LESC_ECM_REG_CH_CN-CHINESE_AU-MAT", "SESU_NAAU_LESC_ECM_REG_CH_CN-CHINESE_MAT", "SESU_NAAU_LESC_ECM_REG_CH_ENGLISH_AUSG-FBA",
    "SESU_NAAU_LESC_ECM_REG_CH_ENGLISH_AUSG-MAT", "SESU_NABR_LESC_ECM_911_CH_ENGLISH_BR-FBA", "SESU_NABR_LESC_ECM_911_CH_ENGLISH_BR-MAT",
    "SESU_NABR_LESC_ECM_REG_CH_ENGLISH_BR-FBA", "SESU_NABR_LESC_ECM_REG_CH_ENGLISH_BR-MAT", "SESU_NABR_LESC_ECM_VIP_CH_ENGLISH_BR-FBA",
    "SESU_NABR_LESC_ECM_VIP_CH_ENGLISH_BR-MAT", "SESU_NAEG_LESC_ECM_911_CH_ENGLISH_ME-MAT", "SESU_NAEG_LESC_ECM_REG_CH_ENGLISH_ME-FBA",
    "SESU_NAEG_LESC_ECM_REG_CH_ENGLISH_ME-MAT", "SESU_NAIN_LESC_ECM_911_CH_ENGLISH_IN-MAT", "SESU_NAIN_LESC_ECM_911_CH_ENGLISH_IN-SDFR",
    "SESU_NAIN_LESC_ECM_REG_CH_ENGLISH_IN-MAT", "SESU_NAIN_LESC_ECM_REG_CH_ENGLISH_IN-SDFR", "SESU_NAJP_LESC_ECM_911_CH_CN-CHINESE_JP-MAT",
    "SESU_NAJP_LESC_ECM_911_CH_CN-CHINESE_MAT", "SESU_NAJP_LESC_ECM_REG_CH_CN-CHINESE_JP-MAT", "SESU_NAJP_LESC_ECM_REG_CH_CN-CHINESE_MAT",
    "SESU_NAJP_LESC_ECM_REG_CH_ENGLISH_JP-SDFR", "SESU_NAMX_LESC_ECM_911_CH_ENGLISH_MX-FBA", "SESU_NAMX_LESC_ECM_911_CH_ENGLISH_MX-MAT",
    "SESU_NAMX_LESC_ECM_REG_CH_ENGLISH_MX-FBA", "SESU_NAMX_LESC_ECM_REG_CH_ENGLISH_MX-MAT", "SESU_NAMX_LESC_ECM_VIP_CH_ENGLISH_MX-FBA",
    "SESU_NAMX_LESC_ECM_VIP_CH_ENGLISH_MX-MAT", "SESU_NASA_LESC_ECM_911_CH_ENGLISH_ME-MAT", "SESU_NASA_LESC_ECM_REG_CH_ENGLISH_ME-FBA",
    "SESU_NASA_LESC_ECM_REG_CH_ENGLISH_ME-MAT", "SESU_NASA_LESC_ECM_VIP_CH_ENGLISH_ME-FBA", "SESU_NASG_LESC_ECM_REG_CH_ENGLISH_AUSG-FBA",
    "SESU_NASG_LESC_ECM_REG_CH_ENGLISH_AUSG-MAT", "SESU_NAUK_LESC_ECM_911_CH_CN-CHINESE_MAT", "SESU_NAUK_LESC_ECM_911_CH_CN-CHINESE_UK-MAT",
    "SESU_NAUK_LESC_ECM_911_CH_ENGLISH_EU-SDFR", "SESU_NAUK_LESC_ECM_911_CH_ENGLISH_EU5-FBA", "SESU_NAUK_LESC_ECM_911_CH_ENGLISH_EU5-MAT",
    "SESU_NAUK_LESC_ECM_REG_CH_CN-CHINESE_MAT", "SESU_NAUK_LESC_ECM_REG_CH_CN-CHINESE_UK-MAT", "SESU_NAUK_LESC_ECM_REG_CH_ENGLISH_EU-SDFR",
    "SESU_NAUK_LESC_ECM_REG_CH_ENGLISH_EU5-FBA", "SESU_NAUK_LESC_ECM_REG_CH_ENGLISH_EU5-MAT", "SESU_NAUK_LESC_ECM_V911_CH_CN-CHINESE_MAT",
    "SESU_NAUK_LESC_ECM_V911_CH_CN-CHINESE_UK-MAT", "SESU_NAUK_LESC_ECM_V911_CH_ENGLISH_EU5-FBA", "SESU_NAUK_LESC_ECM_V911_CH_ENGLISH_EU5-MAT",
    "SESU_NAUK_LESC_ECM_VIP_CH_CN-CHINESE_MAT", "SESU_NAUK_LESC_ECM_VIP_CH_CN-CHINESE_UK-MAT", "SESU_NAUK_LESC_ECM_VIP_CH_ENGLISH_EU-SDFR",
    "SESU_NAUK_LESC_ECM_VIP_CH_ENGLISH_EU5-FBA", "SESU_NAUK_LESC_ECM_VIP_CH_ENGLISH_EU5-MAT", "SESU_NAUS_LESC_ECM_911_CH_CN-CHINESE_MAT",
    "SESU_NAUS_LESC_ECM_911_CH_ENGLISH_NA-FBA", "SESU_NAUS_LESC_ECM_911_CH_ENGLISH_NA-MAT", "SESU_NAUS_LESC_ECM_911_CH_ENGLISH_NA-SDFR",
    "SESU_NAUS_LESC_ECM_REG_CH_CN-CHINESE_MAT", "SESU_NAUS_LESC_ECM_REG_CH_ENGLISH_NA-FBA", "SESU_NAUS_LESC_ECM_REG_CH_ENGLISH_NA-MAT",
    "SESU_NAUS_LESC_ECM_REG_CH_ENGLISH_NA-SDFR", "SESU_NAUS_LESC_ECM_V911_CH_CN-CHINESE_MAT", "SESU_NAUS_LESC_ECM_V911_CH_ENGLISH_NA-FBA",
    "SESU_NAUS_LESC_ECM_V911_CH_ENGLISH_NA-MAT", "SESU_NAUS_LESC_ECM_V911_CH_ENGLISH_NA-SDFR", "SESU_NAUS_LESC_ECM_VIP_CH_CN-CHINESE_MAT",
    "SESU_NAUS_LESC_ECM_VIP_CH_ENGLISH_NA-FBA", "SESU_NAUS_LESC_ECM_VIP_CH_ENGLISH_NA-MAT", "SESU_NAUS_LESC_PCM_911_CH_ENGLISH_NA-FBA",
    "SESU_NAUS_LESC_PCM_911_CH_ENGLISH_NA-MAT", "SESU_NAUS_LESC_PCM_REG_CH_ENGLISH_NA-FBA", "SESU_NAUS_LESC_PCM_REG_CH_ENGLISH_NA-MAT",
    "SESU_NAUS_LESC_PCM_V911_CH_ENGLISH_NA-FBA", "SESU_NAUS_LESC_PCM_V911_CH_ENGLISH_NA-MAT", "SESU_NAUS_LESC_PCM_VIP_CH_ENGLISH_NA-FBA",
    "SESU_NAUS_LESC_PCM_VIP_CH_ENGLISH_NA-MAT", "SESU_NA_FBA_ECM_REG_LESCWI_ENG", "SESU_NA_FBA_ECM_REG_LESC_ENG",
    "SESU_NA_FBA_PCM_REG_LESC_ENG", "SESU_NA_LESC_ECM_REG_STD_ENG_HRO", "SESU_NA_MAT_ECM_REG_LESCWI_ENG",
    "SESU_NA_MAT_ECM_REG_LESC_CNCN", "SESU_NA_MAT_ECM_REG_LESC_ENG", "SESU_NA_MAT_ECM_REG_STD_ENG_SDFR",
    "SESU_NA_MAT_PCM_REG_LESC_ENG", "SESU_SA_FBA_ECM_REG_LESCWI_ENG", "SESU_SA_FBA_ECM_REG_LESC_ENG",
    "SESU_SA_MAT_ECM_REG_LESCWI_ENG", "SESU_SA_MAT_ECM_REG_LESC_ENG", "SESU_SG_FBA_ECM_REG_LESCWI_ENG",
    "SESU_SG_FBA_ECM_REG_LESC_ENG", "SESU_SG_MAT_ECM_REG_LESCWI_ENG", "SESU_SG_MAT_ECM_REG_LESC_ENG"
]

if __name__ == "__main__":
    with engine.connect() as conn:
        for skill in LESC_SKILLS:
            conn.execute(
                text("INSERT INTO skills (skill_code, team_name, is_active) VALUES (:s, 'LESC', TRUE) ON CONFLICT (skill_code) DO NOTHING"),
                {"s": skill}
            )
        conn.commit()
        print(f"✅ Populated {len(LESC_SKILLS)} LESC skills")
